server {
  listen 80;
  client_max_body_size 25m;
  root /usr/share/nginx/html;
  index index.html;

  location /api/     { proxy_pass http://backend:4000; }
  location /uploads/ { proxy_pass http://backend:4000; }
  location /webhook/ { proxy_pass http://backend:4000; }
  location /         { try_files $uri /index.html; }
}
